name: CI

env:
  SERVER: production

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: init node.js
        uses: actions/setup-node@v2
      - name: install
        run: |
          npm i -g pnpm
          pnpm i -g surge
          pnpm i
      - name: deploy-j2d
        run: |
          pnpm build:j2d
          surge ./packages/json2dart/build/ json2dart.surge.sh --token ${{ secrets.SURGE_TOKEN }}
